version: '3'
services:
 sistema-mensageria:
   build: ./api-email
   container_name: sistema-mensageria
   ports:
     - '9090:9090'
   environment:
     - SPRING_MAIL_HOST=smtp.gmail.com
     - SPRING_MAIL_PORT=587
     - SPRING_MAIL_USERNAME=projetosemjava@gmail.com
     - SPRING_MAIL_PASSWORD=hmcu fvma aaeb enzw
     - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
     - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
     - SPRING_RABBITMQ_ADDRESSES=amqps://yarywlxe:ba0HBDJbmfeqE-JbPp4BaKQYVHmch1Ee@prawn.rmq.cloudamqp.com/yarywlxe
   networks:
     - mynetwork
 aplicacao-principal:
   build: ./empresa
   container_name: aplicacao-principal
   ports:
     - '8080:8080'
   environment:
     - SPRING_RABBITMQ_ADDRESSES=amqps://yarywlxe:ba0HBDJbmfeqE-JbPp4BaKQYVHmch1Ee@prawn.rmq.cloudamqp.com/yarywlxe
   networks:
     - mynetwork
#  angular-app:
#    build: ./interface-empresa
#    container_name: angular-app
#    ports:
#      - '8082:80'
#    networks:
#      - mynetwork
networks:
 mynetwork:
   driver: bridge
